// Generated using SwiftGen — https://github.com/SwiftGen/SwiftGen

import SwiftUI

/// Cases to reference for safely initializing colors, like so: `Clr.Fill.primary`
public enum Clr {
  public enum Neutrals {
    public static let trvblack = Color("neutrals/black", bundle: .module)
    public static let trvwhite = Color("neutrals/white", bundle: .module)
  }
  public enum TrvBlue {
    public static let trv100 = Color("trvBlue/100", bundle: .module)
    public static let trv200 = Color("trvBlue/200", bundle: .module)
    public static let trv300 = Color("trvBlue/300", bundle: .module)
    public static let trv50 = Color("trvBlue/50", bundle: .module)
    public static let trv500 = Color("trvBlue/500", bundle: .module)
    public static let trv700 = Color("trvBlue/700", bundle: .module)
    public static let trv900 = Color("trvBlue/900", bundle: .module)
  }
  public enum TrvGreen {
    public static let trv100 = Color("trvGreen/100", bundle: .module)
    public static let trv200 = Color("trvGreen/200", bundle: .module)
    public static let trv300 = Color("trvGreen/300", bundle: .module)
    public static let trv50 = Color("trvGreen/50", bundle: .module)
    public static let trv500 = Color("trvGreen/500", bundle: .module)
    public static let trv700 = Color("trvGreen/700", bundle: .module)
    public static let trv900 = Color("trvGreen/900", bundle: .module)
  }
  public enum TrvJuri {
    public static let trv100 = Color("trvJuri/100", bundle: .module)
    public static let trv200 = Color("trvJuri/200", bundle: .module)
    public static let trv300 = Color("trvJuri/300", bundle: .module)
    public static let trv50 = Color("trvJuri/50", bundle: .module)
    public static let trv500 = Color("trvJuri/500", bundle: .module)
    public static let trv700 = Color("trvJuri/700", bundle: .module)
    public static let trv900 = Color("trvJuri/900", bundle: .module)
  }
  public enum TrvOrange {
    public static let trv100 = Color("trvOrange/100", bundle: .module)
    public static let trv200 = Color("trvOrange/200", bundle: .module)
    public static let trv300 = Color("trvOrange/300", bundle: .module)
    public static let trv50 = Color("trvOrange/50", bundle: .module)
    public static let trv500 = Color("trvOrange/500", bundle: .module)
    public static let trv700 = Color("trvOrange/700", bundle: .module)
    public static let trv900 = Color("trvOrange/900", bundle: .module)
  }
  public enum TrvRed {
    public static let trv100 = Color("trvRed/100", bundle: .module)
    public static let trv200 = Color("trvRed/200", bundle: .module)
    public static let trv300 = Color("trvRed/300", bundle: .module)
    public static let trv50 = Color("trvRed/50", bundle: .module)
    public static let trv500 = Color("trvRed/500", bundle: .module)
    public static let trv600 = Color("trvRed/600", bundle: .module)
    public static let trv700 = Color("trvRed/700", bundle: .module)
  }
}

/// Cases to reference for safely initializing images, like so: `Img.Onboarding.header`
public enum Img {
  public enum Icons {
    public enum Activities {
      public static let adventure24x24 = Image("Icons/Activities/Adventure 24x24", bundle: .module)
      public static let baseball24x24Fill = Image("Icons/Activities/Baseball 24x24 Fill", bundle: .module)
      public static let baseball24x24Line = Image("Icons/Activities/Baseball 24x24 Line", bundle: .module)
      public static let basketball24x24Fill = Image("Icons/Activities/Basketball 24x24 Fill", bundle: .module)
      public static let basketball24x24Line = Image("Icons/Activities/Basketball 24x24 Line", bundle: .module)
      public static let controller24x24Fill = Image("Icons/Activities/Controller 24x24 Fill", bundle: .module)
      public static let controller24x24Line = Image("Icons/Activities/Controller 24x24 Line", bundle: .module)
      public static let darts24x24Fill = Image("Icons/Activities/Darts 24x24 Fill", bundle: .module)
      public static let darts24x24Line = Image("Icons/Activities/Darts 24x24 Line", bundle: .module)
      public static let discoball24x24Fill = Image("Icons/Activities/Discoball 24x24 Fill", bundle: .module)
      public static let discoball24x24Line = Image("Icons/Activities/Discoball 24x24 Line", bundle: .module)
      public static let finish24x24 = Image("Icons/Activities/Finish 24x24", bundle: .module)
      public static let golf24x24Fill = Image("Icons/Activities/Golf 24x24 Fill", bundle: .module)
      public static let golf24x24Line = Image("Icons/Activities/Golf 24x24 Line", bundle: .module)
      public static let guitar24x24FIll = Image("Icons/Activities/Guitar 24x24 FIll", bundle: .module)
      public static let guitar24x24Line = Image("Icons/Activities/Guitar 24x24 Line", bundle: .module)
      public enum Large {
        public static let finish48x48 = Image("Icons/Activities/Large/Finish 48x48", bundle: .module)
        public static let pitch48x48Fill = Image("Icons/Activities/Large/Pitch 48x48 Fill", bundle: .module)
        public static let pitch48x48Line = Image("Icons/Activities/Large/Pitch 48x48 Line", bundle: .module)
        public static let telescope48x48Fill = Image("Icons/Activities/Large/Telescope 48x48 Fill", bundle: .module)
        public static let telescope48x48Line = Image("Icons/Activities/Large/Telescope 48x48 Line", bundle: .module)
        public static let ufo48x48Fill = Image("Icons/Activities/Large/Ufo 48x48 Fill", bundle: .module)
        public static let ufo48x48Line = Image("Icons/Activities/Large/Ufo 48x48 Line", bundle: .module)
        public static let weight48x48Fill = Image("Icons/Activities/Large/Weight 48x48 Fill", bundle: .module)
        public static let weight48x48Line = Image("Icons/Activities/Large/Weight 48x48 Line", bundle: .module)
        public static let xmasDecorations48x48Fill = Image("Icons/Activities/Large/Xmas decorations 48x48 Fill", bundle: .module)
        public static let xmasDecorations48x48Line = Image("Icons/Activities/Large/Xmas decorations 48x48 Line", bundle: .module)
      }
      public static let masks24x24Fill = Image("Icons/Activities/Masks 24x24 Fill", bundle: .module)
      public static let masks24x24Line = Image("Icons/Activities/Masks 24x24 Line", bundle: .module)
      public static let outdoor24x24 = Image("Icons/Activities/Outdoor 24x24", bundle: .module)
      public static let pitch24x24Fill = Image("Icons/Activities/Pitch 24x24 Fill", bundle: .module)
      public static let pitch24x24Line = Image("Icons/Activities/Pitch 24x24 Line", bundle: .module)
      public static let ski24x24Fill = Image("Icons/Activities/Ski 24x24 Fill", bundle: .module)
      public static let ski24x24Line = Image("Icons/Activities/Ski 24x24 Line", bundle: .module)
      public static let telescope24x24Fill = Image("Icons/Activities/Telescope 24x24 Fill", bundle: .module)
      public static let telescope24x24Line = Image("Icons/Activities/Telescope 24x24 Line", bundle: .module)
      public static let tennis24x24Fill = Image("Icons/Activities/Tennis 24x24 Fill", bundle: .module)
      public static let tennis24x24Line = Image("Icons/Activities/Tennis 24x24 Line", bundle: .module)
      public static let trumpet24x24Fill = Image("Icons/Activities/Trumpet 24x24 Fill", bundle: .module)
      public static let trumpet24x24Line = Image("Icons/Activities/Trumpet 24x24 Line", bundle: .module)
      public static let tshirt24x24Fill = Image("Icons/Activities/Tshirt 24x24 Fill", bundle: .module)
      public static let tshirt24x24Line = Image("Icons/Activities/Tshirt 24x24 Line", bundle: .module)
      public static let weight24x24Fill = Image("Icons/Activities/Weight 24x24 Fill", bundle: .module)
      public static let weight24x24Line = Image("Icons/Activities/Weight 24x24 Line", bundle: .module)
    }
    public enum Amenities {
      public static let atm24x24Fill = Image("Icons/Amenities/ATM 24x24 Fill", bundle: .module)
      public static let atm24x24Line = Image("Icons/Amenities/ATM 24x24 Line", bundle: .module)
      public static let armchair24x24Line1 = Image("Icons/Amenities/Armchair 24x24 Line-1", bundle: .module)
      public static let armchair24x24Line = Image("Icons/Amenities/Armchair 24x24 Line", bundle: .module)
      public static let babyBottle24x24Fill = Image("Icons/Amenities/Baby bottle 24x24 Fill", bundle: .module)
      public static let babyBottle24x24Line = Image("Icons/Amenities/Baby bottle 24x24 Line", bundle: .module)
      public static let balcony24x24Fill = Image("Icons/Amenities/Balcony 24x24 Fill", bundle: .module)
      public static let balcony24x24Line = Image("Icons/Amenities/Balcony 24x24 Line", bundle: .module)
      public static let bathub24x24Fill = Image("Icons/Amenities/Bathub 24x24 Fill", bundle: .module)
      public static let bathub24x24Line = Image("Icons/Amenities/Bathub 24x24 Line", bundle: .module)
      public static let beach24x24Fill = Image("Icons/Amenities/Beach 24x24 Fill", bundle: .module)
      public static let beach24x24Line = Image("Icons/Amenities/Beach 24x24 Line", bundle: .module)
      public static let bedDouble24x24Fill = Image("Icons/Amenities/Bed double 24x24 Fill", bundle: .module)
      public static let bedDouble24x24Line = Image("Icons/Amenities/Bed double 24x24 Line", bundle: .module)
      public static let bedSingle24x24Fill = Image("Icons/Amenities/Bed single 24x24 Fill", bundle: .module)
      public static let bedSingle24x24Line = Image("Icons/Amenities/Bed single 24x24 Line", bundle: .module)
      public static let bedSmall24x24Fill = Image("Icons/Amenities/Bed small 24x24 Fill", bundle: .module)
      public static let bedSmall24x24Line = Image("Icons/Amenities/Bed small 24x24 Line", bundle: .module)
      public static let broom24x24Fill = Image("Icons/Amenities/Broom 24x24 Fill", bundle: .module)
      public static let broom24x24Line = Image("Icons/Amenities/Broom 24x24 Line", bundle: .module)
      public static let canteen24x24Line1 = Image("Icons/Amenities/Canteen 24x24 Line-1", bundle: .module)
      public static let canteen24x24Line = Image("Icons/Amenities/Canteen 24x24 Line", bundle: .module)
      public static let cigarette24x24Fill = Image("Icons/Amenities/Cigarette 24x24 Fill", bundle: .module)
      public static let cigarette24x24Line = Image("Icons/Amenities/Cigarette 24x24 Line", bundle: .module)
      public static let cigaretteCrossed24x24Fill = Image("Icons/Amenities/Cigarette crossed 24x24 Fill", bundle: .module)
      public static let cigaretteCrossed24x24Line = Image("Icons/Amenities/Cigarette crossed 24x24 Line", bundle: .module)
      public static let cocktail24x24Fill = Image("Icons/Amenities/Cocktail 24x24 Fill", bundle: .module)
      public static let cocktail24x24Line = Image("Icons/Amenities/Cocktail 24x24 Line", bundle: .module)
      public static let coffee24x24Fill = Image("Icons/Amenities/Coffee 24x24 Fill", bundle: .module)
      public static let coffee24x24Line = Image("Icons/Amenities/Coffee 24x24 Line", bundle: .module)
      public static let diamond24x24Fill = Image("Icons/Amenities/Diamond 24x24 Fill", bundle: .module)
      public static let diamond24x24Line = Image("Icons/Amenities/Diamond 24x24 Line", bundle: .module)
      public static let door24x24Fill = Image("Icons/Amenities/Door 24x24 Fill", bundle: .module)
      public static let door24x24Line = Image("Icons/Amenities/Door 24x24 Line", bundle: .module)
      public static let elevator24x24Fill = Image("Icons/Amenities/Elevator 24x24 Fill", bundle: .module)
      public static let elevator24x24Line = Image("Icons/Amenities/Elevator 24x24 Line", bundle: .module)
      public static let firstAid24x24Fill = Image("Icons/Amenities/First aid 24x24 Fill", bundle: .module)
      public static let firstAid24x24Line = Image("Icons/Amenities/First aid 24x24 Line", bundle: .module)
      public static let food24x24Fill = Image("Icons/Amenities/Food 24x24 Fill", bundle: .module)
      public static let food24x24Line = Image("Icons/Amenities/Food 24x24 Line", bundle: .module)
      public static let fountain24x24Fill = Image("Icons/Amenities/Fountain 24x24 Fill", bundle: .module)
      public static let fountain24x24Line = Image("Icons/Amenities/Fountain 24x24 Line", bundle: .module)
      public static let grill24x24Fill = Image("Icons/Amenities/Grill 24x24 Fill", bundle: .module)
      public static let grill24x24Line = Image("Icons/Amenities/Grill 24x24 Line", bundle: .module)
      public static let hairdryer24x24Fill = Image("Icons/Amenities/Hairdryer 24x24 Fill", bundle: .module)
      public static let hairdryer24x24Line = Image("Icons/Amenities/Hairdryer 24x24 Line", bundle: .module)
      public static let kitchen24x24Fill = Image("Icons/Amenities/Kitchen 24x24 Fill", bundle: .module)
      public static let kitchen24x24Line = Image("Icons/Amenities/Kitchen 24x24 Line", bundle: .module)
      public enum Large {
        public static let babyBottle48x48Fill = Image("Icons/Amenities/Large/Baby bottle 48x48 Fill", bundle: .module)
        public static let babyBottle48x48Line = Image("Icons/Amenities/Large/Baby bottle 48x48 Line", bundle: .module)
        public static let bathtub48x48Fill = Image("Icons/Amenities/Large/Bathtub 48x48 Fill", bundle: .module)
        public static let bathtub48x48Line = Image("Icons/Amenities/Large/Bathtub 48x48 Line", bundle: .module)
        public static let coffee48x48Fill = Image("Icons/Amenities/Large/Coffee 48x48 Fill", bundle: .module)
        public static let coffee48x48Line = Image("Icons/Amenities/Large/Coffee 48x48 Line", bundle: .module)
        public static let door48x48Fill = Image("Icons/Amenities/Large/Door 48x48 Fill", bundle: .module)
        public static let door48x48Line = Image("Icons/Amenities/Large/Door 48x48 Line", bundle: .module)
        public static let hairdryer48x48Fill = Image("Icons/Amenities/Large/Hairdryer 48x48 Fill", bundle: .module)
        public static let hairdryer48x48Line = Image("Icons/Amenities/Large/Hairdryer 48x48 Line", bundle: .module)
        public static let oil48x48Fill = Image("Icons/Amenities/Large/Oil 48x48 Fill", bundle: .module)
        public static let oil48x48Line = Image("Icons/Amenities/Large/Oil 48x48 Line", bundle: .module)
        public static let pool48x48FIll = Image("Icons/Amenities/Large/Pool 48x48 FIll", bundle: .module)
        public static let pool48x48Line = Image("Icons/Amenities/Large/Pool 48x48 Line", bundle: .module)
        public static let receptionBell48x48Fill = Image("Icons/Amenities/Large/Reception bell 48x48 Fill", bundle: .module)
        public static let receptionBell48x48Line = Image("Icons/Amenities/Large/Reception bell 48x48 Line", bundle: .module)
        public static let restaurant48x48Fill = Image("Icons/Amenities/Large/Restaurant 48x48 Fill", bundle: .module)
        public static let restaurant48x48Line = Image("Icons/Amenities/Large/Restaurant 48x48 Line", bundle: .module)
        public static let sofaLamp48x48Fill = Image("Icons/Amenities/Large/Sofa lamp 48x48 Fill", bundle: .module)
        public static let sofaLamp48x48Line = Image("Icons/Amenities/Large/Sofa lamp 48x48 Line", bundle: .module)
        public static let spa48x48Fill = Image("Icons/Amenities/Large/Spa 48x48 Fill", bundle: .module)
        public static let spa48x48Line = Image("Icons/Amenities/Large/Spa 48x48 Line", bundle: .module)
      }
      public static let parking24x24Fill = Image("Icons/Amenities/Parking 24x24 Fill", bundle: .module)
      public static let parking24x24Line = Image("Icons/Amenities/Parking 24x24 Line", bundle: .module)
      public static let paw24x24Fill = Image("Icons/Amenities/Paw 24x24 Fill", bundle: .module)
      public static let paw24x24Line = Image("Icons/Amenities/Paw 24x24 Line", bundle: .module)
      public static let pool24x24Fill = Image("Icons/Amenities/Pool 24x24 Fill", bundle: .module)
      public static let pool24x24Line = Image("Icons/Amenities/Pool 24x24 Line", bundle: .module)
      public static let receptionBell24x24Fill = Image("Icons/Amenities/Reception bell 24x24 Fill", bundle: .module)
      public static let receptionBell24x24Line = Image("Icons/Amenities/Reception bell 24x24 Line", bundle: .module)
      public static let restaurant24x24Fill = Image("Icons/Amenities/Restaurant 24x24 Fill", bundle: .module)
      public static let restaurant24x24Line = Image("Icons/Amenities/Restaurant 24x24 Line", bundle: .module)
      public static let safebox24x24Fill = Image("Icons/Amenities/Safebox 24x24 Fill", bundle: .module)
      public static let safebox24x24Line = Image("Icons/Amenities/Safebox 24x24 Line", bundle: .module)
      public static let shoppingbag24x24Fill = Image("Icons/Amenities/Shoppingbag 24x24 Fill", bundle: .module)
      public static let shoppingbag24x24Line = Image("Icons/Amenities/Shoppingbag 24x24 Line", bundle: .module)
      public static let shower24x24Fill = Image("Icons/Amenities/Shower 24x24 Fill", bundle: .module)
      public static let shower24x24Line = Image("Icons/Amenities/Shower 24x24 Line", bundle: .module)
      public static let snowflake24x24 = Image("Icons/Amenities/Snowflake 24x24", bundle: .module)
      public static let spa24x24Fill = Image("Icons/Amenities/Spa 24x24 Fill", bundle: .module)
      public static let spa24x24Line = Image("Icons/Amenities/Spa 24x24 Line", bundle: .module)
      public static let stairs24x24Line = Image("Icons/Amenities/Stairs 24x24 Line", bundle: .module)
      public static let stroller24x24Fill = Image("Icons/Amenities/Stroller 24x24 Fill", bundle: .module)
      public static let stroller24x24Line = Image("Icons/Amenities/Stroller 24x24 Line", bundle: .module)
      public static let surface24x24Fill = Image("Icons/Amenities/Surface 24x24 Fill", bundle: .module)
      public static let surface24x24Line = Image("Icons/Amenities/Surface 24x24 Line", bundle: .module)
      public static let tea24x24Line1 = Image("Icons/Amenities/Tea 24x24 Line-1", bundle: .module)
      public static let tea24x24Line = Image("Icons/Amenities/Tea 24x24 Line", bundle: .module)
      public static let towel24x24Fill = Image("Icons/Amenities/Towel 24x24 Fill", bundle: .module)
      public static let towel24x24Line = Image("Icons/Amenities/Towel 24x24 Line", bundle: .module)
      public static let washingMachine24x24Fill = Image("Icons/Amenities/Washing machine 24x24 Fill", bundle: .module)
      public static let washingMachine24x24Line = Image("Icons/Amenities/Washing machine 24x24 Line", bundle: .module)
    }
    public enum Buildings {
      public static let architecture24x24Line = Image("Icons/Buildings/Architecture 24x24 Line", bundle: .module)
      public static let building24x24Line1 = Image("Icons/Buildings/Building 24x24 Line-1", bundle: .module)
      public static let building24x24Line = Image("Icons/Buildings/Building 24x24 Line", bundle: .module)
      public static let grocerystore24x24Fill = Image("Icons/Buildings/Grocerystore 24x24 Fill", bundle: .module)
      public static let grocerystore24x24Line = Image("Icons/Buildings/Grocerystore 24x24 Line", bundle: .module)
      public static let history24x24Line = Image("Icons/Buildings/History 24x24 Line", bundle: .module)
      public static let hotel24x24Fill = Image("Icons/Buildings/Hotel 24x24 Fill", bundle: .module)
      public static let hotel24x24Line = Image("Icons/Buildings/Hotel 24x24 Line", bundle: .module)
      public static let hotelchain24x24Fill = Image("Icons/Buildings/Hotelchain 24x24 Fill", bundle: .module)
      public static let hotelchain24x24Line = Image("Icons/Buildings/Hotelchain 24x24 Line", bundle: .module)
      public static let house24x24Fill = Image("Icons/Buildings/House 24x24 Fill", bundle: .module)
      public static let house24x24Line = Image("Icons/Buildings/House 24x24 Line", bundle: .module)
      public static let houseArrow24x24Fill = Image("Icons/Buildings/House arrow 24x24 Fill", bundle: .module)
      public static let houseArrow24x24Line = Image("Icons/Buildings/House arrow 24x24 Line", bundle: .module)
      public static let houseDetails24x24Fill = Image("Icons/Buildings/House details 24x24 Fill", bundle: .module)
      public static let houseDetails24x24Line = Image("Icons/Buildings/House details 24x24 Line", bundle: .module)
      public static let houseRoof24x24Fill = Image("Icons/Buildings/House roof 24x24 Fill", bundle: .module)
      public static let houseRoof24x24Line = Image("Icons/Buildings/House roof 24x24 Line", bundle: .module)
      public enum Large {
        public static let alternativeAccommodations48x48Fill = Image("Icons/Buildings/Large/Alternative accommodations 48x48 Fill", bundle: .module)
        public static let alternativeAccommodations48x48Line = Image("Icons/Buildings/Large/Alternative accommodations 48x48 Line", bundle: .module)
        public static let houseRoof48x48Fill = Image("Icons/Buildings/Large/House roof 48x48 Fill", bundle: .module)
        public static let houseRoof48x48Line = Image("Icons/Buildings/Large/House roof 48x48 Line", bundle: .module)
        public static let houseRoofList48x48Fill = Image("Icons/Buildings/Large/House roof list 48x48 Fill", bundle: .module)
        public static let houseRoofList48x48Line = Image("Icons/Buildings/Large/House roof list 48x48 Line", bundle: .module)
        public static let houseStaff48x48Fill1 = Image("Icons/Buildings/Large/House staff 48x48 Fill-1", bundle: .module)
        public static let houseStaff48x48Fill = Image("Icons/Buildings/Large/House staff 48x48 Fill", bundle: .module)
        public static let houseStaff48x48Line1 = Image("Icons/Buildings/Large/House staff 48x48 Line-1", bundle: .module)
        public static let houseStaff48x48Line = Image("Icons/Buildings/Large/House staff 48x48 Line", bundle: .module)
        public static let houseTick48x48Fill = Image("Icons/Buildings/Large/House tick 48x48 Fill", bundle: .module)
        public static let houseTick48x48Line = Image("Icons/Buildings/Large/House tick 48x48 Line", bundle: .module)
      }
      public static let museum24x24Fill = Image("Icons/Buildings/Museum 24x24 Fill", bundle: .module)
      public static let museum24x24Line = Image("Icons/Buildings/Museum 24x24 Line", bundle: .module)
      public static let tent24x24Fill = Image("Icons/Buildings/tent 24x24 Fill", bundle: .module)
      public static let tent24x24Line = Image("Icons/Buildings/tent 24x24 Line", bundle: .module)
    }
    public enum Cta {
      public static let info = Image("Icons/CTA/Info", bundle: .module)
      public static let maps = Image("Icons/CTA/Maps", bundle: .module)
      public static let sort = Image("Icons/CTA/Sort", bundle: .module)
    }
    public enum Content {
      public static let bars24x24Fill = Image("Icons/Content/Bars 24x24 Fill", bundle: .module)
      public static let bars24x24Line = Image("Icons/Content/Bars 24x24 Line", bundle: .module)
      public static let barsAscending24x24Fill = Image("Icons/Content/Bars ascending 24x24 Fill", bundle: .module)
      public static let barsAscending24x24Line = Image("Icons/Content/Bars ascending 24x24 Line", bundle: .module)
      public static let book24x24Fill = Image("Icons/Content/Book 24x24 Fill", bundle: .module)
      public static let book24x24Line = Image("Icons/Content/Book 24x24 Line", bundle: .module)
      public static let center24x24Fill = Image("Icons/Content/Center 24x24 Fill", bundle: .module)
      public static let center24x24Line = Image("Icons/Content/Center 24x24 Line", bundle: .module)
      public static let clapperboard24x24Fill = Image("Icons/Content/Clapperboard 24x24 Fill", bundle: .module)
      public static let clapperboard24x24Line = Image("Icons/Content/Clapperboard 24x24 Line", bundle: .module)
      public static let comment24x24Fill = Image("Icons/Content/Comment 24x24 Fill", bundle: .module)
      public static let comment24x24Line = Image("Icons/Content/Comment 24x24 Line", bundle: .module)
      public static let cube24x24Fill = Image("Icons/Content/Cube 24x24 Fill", bundle: .module)
      public static let cube24x24Line = Image("Icons/Content/Cube 24x24 Line", bundle: .module)
      public static let cycle24x24Fill = Image("Icons/Content/Cycle 24x24 Fill", bundle: .module)
      public static let cycle24x24Line = Image("Icons/Content/Cycle 24x24 Line", bundle: .module)
      public static let description24x24Fill = Image("Icons/Content/Description 24x24 Fill", bundle: .module)
      public static let description24x24Line = Image("Icons/Content/Description 24x24 Line", bundle: .module)
      public static let details24x24Fill = Image("Icons/Content/Details 24x24 Fill", bundle: .module)
      public static let details24x24Line = Image("Icons/Content/Details 24x24 Line", bundle: .module)
      public static let drawer24x24Fill = Image("Icons/Content/Drawer 24x24 Fill", bundle: .module)
      public static let drawer24x24Line = Image("Icons/Content/Drawer 24x24 Line", bundle: .module)
      public static let file24x24Fill = Image("Icons/Content/File 24x24 Fill", bundle: .module)
      public static let file24x24Line = Image("Icons/Content/File 24x24 Line", bundle: .module)
      public static let folder24x24Fill = Image("Icons/Content/Folder 24x24 Fill", bundle: .module)
      public static let folder24x24Line = Image("Icons/Content/Folder 24x24 Line", bundle: .module)
      public static let folderOpen24x24Fill = Image("Icons/Content/Folder open 24x24 Fill", bundle: .module)
      public static let folderOpen24x24Line = Image("Icons/Content/Folder open 24x24 Line", bundle: .module)
      public static let growth24x24Fill = Image("Icons/Content/Growth 24x24 Fill", bundle: .module)
      public static let growth24x24Line = Image("Icons/Content/Growth 24x24 Line", bundle: .module)
      public enum Large {
        public static let description48x48Fill = Image("Icons/Content/Large/Description 48x48 Fill", bundle: .module)
        public static let description48x48Line = Image("Icons/Content/Large/Description 48x48 Line", bundle: .module)
        public static let growth48x48Fill = Image("Icons/Content/Large/Growth 48x48 Fill", bundle: .module)
        public static let growth48x48Line = Image("Icons/Content/Large/Growth 48x48 Line", bundle: .module)
        public static let growthMoney48x48Fill = Image("Icons/Content/Large/Growth money 48x48 Fill", bundle: .module)
        public static let growthMoney48x48Line = Image("Icons/Content/Large/Growth money 48x48 Line", bundle: .module)
        public static let pictureFilm48x48Fill = Image("Icons/Content/Large/Picture film 48x48 Fill", bundle: .module)
        public static let pictureFilm48x48Line = Image("Icons/Content/Large/Picture film 48x48 Line", bundle: .module)
      }
      public static let layers24x24Fill = Image("Icons/Content/Layers 24x24 Fill", bundle: .module)
      public static let layers24x24Line = Image("Icons/Content/Layers 24x24 Line", bundle: .module)
      public static let musicNote24x24Fill = Image("Icons/Content/Music note 24x24 Fill", bundle: .module)
      public static let musicNote24x24Line = Image("Icons/Content/Music note 24x24 Line", bundle: .module)
      public static let network24x24Fill = Image("Icons/Content/Network 24x24 Fill", bundle: .module)
      public static let network24x24Line = Image("Icons/Content/Network 24x24 Line", bundle: .module)
      public static let news24x24Fill = Image("Icons/Content/News 24x24 Fill", bundle: .module)
      public static let news24x24Line = Image("Icons/Content/News 24x24 Line", bundle: .module)
      public static let newspaper24x24Fill = Image("Icons/Content/Newspaper 24x24 Fill", bundle: .module)
      public static let newspaper24x24Line = Image("Icons/Content/Newspaper 24x24 Line", bundle: .module)
      public static let picture24x24Fill = Image("Icons/Content/Picture 24x24 Fill", bundle: .module)
      public static let picture24x24Line = Image("Icons/Content/Picture 24x24 Line", bundle: .module)
      public static let pictureFilm24x24Fill = Image("Icons/Content/Picture film 24x24 Fill", bundle: .module)
      public static let pictureFilm24x24Line = Image("Icons/Content/Picture film 24x24 Line", bundle: .module)
      public static let pictures24x24Fill = Image("Icons/Content/Pictures 24x24 Fill", bundle: .module)
      public static let pictures24x24Line = Image("Icons/Content/Pictures 24x24 Line", bundle: .module)
      public static let piechart24x24Fill = Image("Icons/Content/Piechart 24x24 Fill", bundle: .module)
      public static let piechart24x24Line = Image("Icons/Content/Piechart 24x24 Line", bundle: .module)
      public static let proportion24x24Fill = Image("Icons/Content/Proportion 24x24 Fill", bundle: .module)
      public static let proportion24x24Line = Image("Icons/Content/Proportion 24x24 Line", bundle: .module)
      public static let statistics24x24Fill = Image("Icons/Content/Statistics 24x24 Fill", bundle: .module)
      public static let statistics24x24Line = Image("Icons/Content/Statistics 24x24 Line", bundle: .module)
      public static let tag24x24Fill = Image("Icons/Content/Tag 24x24 Fill", bundle: .module)
      public static let tag24x24Line = Image("Icons/Content/Tag 24x24 Line", bundle: .module)
      public static let tagCrossed24x24Fill = Image("Icons/Content/Tag crossed 24x24 Fill", bundle: .module)
      public static let tagCrossed24x24Line = Image("Icons/Content/Tag crossed 24x24 Line", bundle: .module)
    }
    public static let countriesAE = Image("Icons/Countries=AE", bundle: .module)
    public static let countriesAR = Image("Icons/Countries=AR", bundle: .module)
    public static let countriesAT = Image("Icons/Countries=AT", bundle: .module)
    public static let countriesAU = Image("Icons/Countries=AU", bundle: .module)
    public static let countriesBE = Image("Icons/Countries=BE", bundle: .module)
    public static let countriesBG = Image("Icons/Countries=BG", bundle: .module)
    public static let countriesBH = Image("Icons/Countries=BH", bundle: .module)
    public static let countriesBR = Image("Icons/Countries=BR", bundle: .module)
    public static let countriesCA = Image("Icons/Countries=CA", bundle: .module)
    public static let countriesCH = Image("Icons/Countries=CH", bundle: .module)
    public static let countriesCL = Image("Icons/Countries=CL", bundle: .module)
    public static let countriesCN = Image("Icons/Countries=CN", bundle: .module)
    public static let countriesCO = Image("Icons/Countries=CO", bundle: .module)
    public static let countriesCZ = Image("Icons/Countries=CZ", bundle: .module)
    public static let countriesDE = Image("Icons/Countries=DE", bundle: .module)
    public static let countriesDJ = Image("Icons/Countries=DJ", bundle: .module)
    public static let countriesDK = Image("Icons/Countries=DK", bundle: .module)
    public static let countriesDZ = Image("Icons/Countries=DZ", bundle: .module)
    public static let countriesEC = Image("Icons/Countries=EC", bundle: .module)
    public static let countriesEG = Image("Icons/Countries=EG", bundle: .module)
    public static let countriesER = Image("Icons/Countries=ER", bundle: .module)
    public static let countriesES = Image("Icons/Countries=ES", bundle: .module)
    public static let countriesFI = Image("Icons/Countries=FI", bundle: .module)
    public static let countriesFR = Image("Icons/Countries=FR", bundle: .module)
    public static let countriesGB = Image("Icons/Countries=GB", bundle: .module)
    public static let countriesGR = Image("Icons/Countries=GR", bundle: .module)
    public static let countriesHK = Image("Icons/Countries=HK", bundle: .module)
    public static let countriesHR = Image("Icons/Countries=HR", bundle: .module)
    public static let countriesHU = Image("Icons/Countries=HU", bundle: .module)
    public static let countriesID = Image("Icons/Countries=ID", bundle: .module)
    public static let countriesIE = Image("Icons/Countries=IE", bundle: .module)
    public static let countriesIL = Image("Icons/Countries=IL", bundle: .module)
    public static let countriesIN = Image("Icons/Countries=IN", bundle: .module)
    public static let countriesIQ = Image("Icons/Countries=IQ", bundle: .module)
    public static let countriesIT = Image("Icons/Countries=IT", bundle: .module)
    public static let countriesJO = Image("Icons/Countries=JO", bundle: .module)
    public static let countriesJP = Image("Icons/Countries=JP", bundle: .module)
    public static let countriesKM = Image("Icons/Countries=KM", bundle: .module)
    public static let countriesKR = Image("Icons/Countries=KR", bundle: .module)
    public static let countriesKW = Image("Icons/Countries=KW", bundle: .module)
    public static let countriesLB = Image("Icons/Countries=LB", bundle: .module)
    public static let countriesLY = Image("Icons/Countries=LY", bundle: .module)
    public static let countriesMA = Image("Icons/Countries=MA", bundle: .module)
    public static let countriesMR = Image("Icons/Countries=MR", bundle: .module)
    public static let countriesMX = Image("Icons/Countries=MX", bundle: .module)
    public static let countriesMY = Image("Icons/Countries=MY", bundle: .module)
    public static let countriesNL = Image("Icons/Countries=NL", bundle: .module)
    public static let countriesNO = Image("Icons/Countries=NO", bundle: .module)
    public static let countriesNZ = Image("Icons/Countries=NZ", bundle: .module)
    public static let countriesOM = Image("Icons/Countries=OM", bundle: .module)
    public static let countriesPE = Image("Icons/Countries=PE", bundle: .module)
    public static let countriesPH = Image("Icons/Countries=PH", bundle: .module)
    public static let countriesPL = Image("Icons/Countries=PL", bundle: .module)
    public static let countriesPS = Image("Icons/Countries=PS", bundle: .module)
    public static let countriesPT = Image("Icons/Countries=PT", bundle: .module)
    public static let countriesQA = Image("Icons/Countries=QA", bundle: .module)
    public static let countriesRO = Image("Icons/Countries=RO", bundle: .module)
    public static let countriesRS = Image("Icons/Countries=RS", bundle: .module)
    public static let countriesRU = Image("Icons/Countries=RU", bundle: .module)
    public static let countriesSA = Image("Icons/Countries=SA", bundle: .module)
    public static let countriesSE = Image("Icons/Countries=SE", bundle: .module)
    public static let countriesSG = Image("Icons/Countries=SG", bundle: .module)
    public static let countriesSI = Image("Icons/Countries=SI", bundle: .module)
    public static let countriesSK = Image("Icons/Countries=SK", bundle: .module)
    public static let countriesSO = Image("Icons/Countries=SO", bundle: .module)
    public static let countriesSS = Image("Icons/Countries=SS", bundle: .module)
    public static let countriesTH = Image("Icons/Countries=TH", bundle: .module)
    public static let countriesTN = Image("Icons/Countries=TN", bundle: .module)
    public static let countriesTR = Image("Icons/Countries=TR", bundle: .module)
    public static let countriesUS = Image("Icons/Countries=US", bundle: .module)
    public static let countriesUY = Image("Icons/Countries=UY", bundle: .module)
    public static let countriesVN = Image("Icons/Countries=VN", bundle: .module)
    public static let countriesYE = Image("Icons/Countries=YE", bundle: .module)
    public static let creditCards = Image("Icons/CreditCards", bundle: .module)
    public enum Dealform {
      public static let calendar = Image("Icons/Dealform/Calendar", bundle: .module)
      public static let filters = Image("Icons/Dealform/Filters", bundle: .module)
      public static let location = Image("Icons/Dealform/Location", bundle: .module)
      public static let multipleGuests = Image("Icons/Dealform/Multiple Guests", bundle: .module)
      public static let oneGuest = Image("Icons/Dealform/One Guest", bundle: .module)
      public enum Ssg {
        public static let airport = Image("Icons/Dealform/SSG/Airport", bundle: .module)
        public static let concept = Image("Icons/Dealform/SSG/Concept", bundle: .module)
        public static let currentLocation = Image("Icons/Dealform/SSG/Current Location", bundle: .module)
        public static let hotels = Image("Icons/Dealform/SSG/Hotels", bundle: .module)
        public static let location = Image("Icons/Dealform/SSG/Location", bundle: .module)
        public static let poi = Image("Icons/Dealform/SSG/POI", bundle: .module)
        public static let recents = Image("Icons/Dealform/SSG/Recents", bundle: .module)
      }
      public static let search = Image("Icons/Dealform/Search", bundle: .module)
      public static let sortDisabled = Image("Icons/Dealform/Sort Disabled", bundle: .module)
      public static let sort = Image("Icons/Dealform/Sort", bundle: .module)
      public static let twoGuests = Image("Icons/Dealform/Two Guests", bundle: .module)
    }
    public enum Functional {
      public static let arrowCircle24x24Fill = Image("Icons/Functional/Arrow circle 24x24 Fill", bundle: .module)
      public static let arrowCircle24x24Line = Image("Icons/Functional/Arrow circle 24x24 Line", bundle: .module)
      public static let arrowDown18x18 = Image("Icons/Functional/Arrow(down) 18x18", bundle: .module)
      public static let arrowDown24x24 = Image("Icons/Functional/Arrow(down) 24x24", bundle: .module)
      public static let arrowDown36x36 = Image("Icons/Functional/Arrow(down) 36x36", bundle: .module)
      public static let arrowDown44x44 = Image("Icons/Functional/Arrow(down) 44x44", bundle: .module)
      public static let arrowLeft18x18 = Image("Icons/Functional/Arrow(left) 18x18", bundle: .module)
      public static let arrowLeft24x24 = Image("Icons/Functional/Arrow(left) 24x24", bundle: .module)
      public static let arrowLeft36x36 = Image("Icons/Functional/Arrow(left) 36x36", bundle: .module)
      public static let arrowLeft44x44 = Image("Icons/Functional/Arrow(left) 44x44", bundle: .module)
      public static let arrowRight18x18 = Image("Icons/Functional/Arrow(right) 18x18", bundle: .module)
      public static let arrowRight24x24 = Image("Icons/Functional/Arrow(right) 24x24", bundle: .module)
      public static let arrowRight36x36 = Image("Icons/Functional/Arrow(right) 36x36", bundle: .module)
      public static let arrowRight44x44 = Image("Icons/Functional/Arrow(right) 44x44", bundle: .module)
      public static let arrowUp18x18 = Image("Icons/Functional/Arrow(up) 18x18", bundle: .module)
      public static let arrowUp24x24 = Image("Icons/Functional/Arrow(up) 24x24", bundle: .module)
      public static let arrowUp36x36 = Image("Icons/Functional/Arrow(up) 36x36", bundle: .module)
      public static let arrowUp44x44 = Image("Icons/Functional/Arrow(up) 44x44", bundle: .module)
      public static let arrow = Image("Icons/Functional/Arrow", bundle: .module)
      public static let arrows324x24 = Image("Icons/Functional/Arrows 3 24x24", bundle: .module)
      public static let ascending24x24 = Image("Icons/Functional/Ascending 24x24", bundle: .module)
      public static let close18x18 = Image("Icons/Functional/Close 18x18", bundle: .module)
      public static let close24x24 = Image("Icons/Functional/Close 24x24", bundle: .module)
      public static let close36x36 = Image("Icons/Functional/Close 36x36", bundle: .module)
      public static let close44x44 = Image("Icons/Functional/Close 44x44", bundle: .module)
      public static let closeCircle24x24Fill = Image("Icons/Functional/Close circle 24x24 Fill", bundle: .module)
      public static let closeCircle24x24Line = Image("Icons/Functional/Close circle 24x24 Line", bundle: .module)
      public static let close = Image("Icons/Functional/Close", bundle: .module)
      public static let descending24x24 = Image("Icons/Functional/Descending 24x24", bundle: .module)
      public static let direction24x24 = Image("Icons/Functional/Direction 24x24", bundle: .module)
      public static let fullscreen24x24 = Image("Icons/Functional/Fullscreen 24x24", bundle: .module)
      public static let info24x24 = Image("Icons/Functional/Info 24x24", bundle: .module)
      public static let infoCircle24x24Fill = Image("Icons/Functional/Info circle 24x24 Fill", bundle: .module)
      public static let infoCircle24x24Line = Image("Icons/Functional/Info circle 24x24 Line", bundle: .module)
      public static let list24x24 = Image("Icons/Functional/List 24x24", bundle: .module)
      public static let magnifier24x24Fill = Image("Icons/Functional/Magnifier 24x24 Fill", bundle: .module)
      public static let magnifier24x24Line = Image("Icons/Functional/Magnifier 24x24 Line", bundle: .module)
      public static let magnifierMinus24x24Fill = Image("Icons/Functional/Magnifier minus 24x24 Fill", bundle: .module)
      public static let magnifierMinus24x24Line = Image("Icons/Functional/Magnifier minus 24x24 Line", bundle: .module)
      public static let magnifierPlus24x24Fill = Image("Icons/Functional/Magnifier plus 24x24 Fill", bundle: .module)
      public static let magnifierPlus24x24Line = Image("Icons/Functional/Magnifier plus 24x24 Line", bundle: .module)
      public static let menu24x24 = Image("Icons/Functional/Menu 24x24", bundle: .module)
      public static let minus24x24 = Image("Icons/Functional/Minus 24x24", bundle: .module)
      public static let minusCircle24x24Fill = Image("Icons/Functional/Minus circle 24x24 Fill", bundle: .module)
      public static let minusCircle24x24Line = Image("Icons/Functional/Minus circle 24x24 Line", bundle: .module)
      public static let narrowDown24x24 = Image("Icons/Functional/Narrow down 24x24", bundle: .module)
      public static let plus24x24 = Image("Icons/Functional/Plus 24x24", bundle: .module)
      public static let plusCircle24x24Fill = Image("Icons/Functional/Plus circle 24x24 Fill", bundle: .module)
      public static let plusCircle24x24Line = Image("Icons/Functional/Plus circle 24x24 Line", bundle: .module)
      public static let pointingArrow24x24 = Image("Icons/Functional/Pointing arrow 24x24", bundle: .module)
      public static let sort24x24 = Image("Icons/Functional/Sort 24x24", bundle: .module)
      public static let tick24x24 = Image("Icons/Functional/Tick 24x24", bundle: .module)
      public static let tickCircle24x24Fill = Image("Icons/Functional/Tick circle 24x24 Fill", bundle: .module)
      public static let tickCircle24x24Line = Image("Icons/Functional/Tick circle 24x24 Line", bundle: .module)
    }
    public enum Icons {
      public enum Activities {
        public enum Gym24x24Line {
          public static let disabled = Image("Icons/Icons/Activities/Gym 24x24 Line/Disabled", bundle: .module)
        }
        public static let gym24x24Line = Image("Icons/Icons/Activities/Gym 24x24 Line", bundle: .module)
      }
      public enum Hotel {
        public enum AC24x24 {
          public static let disabled = Image("Icons/Icons/Hotel/AC 24x24/Disabled", bundle: .module)
        }
        public static let ac24x24Line = Image("Icons/Icons/Hotel/AC 24x24 Line", bundle: .module)
        public enum Nightlife24x24Line {
          public static let disabled = Image("Icons/Icons/Hotel/Nightlife 24x24 Line/Disabled", bundle: .module)
        }
        public static let nightlife24x24Line = Image("Icons/Icons/Hotel/Nightlife 24x24 Line", bundle: .module)
        public enum Parking24x24Line {
          public static let disabled = Image("Icons/Icons/Hotel/Parking 24x24 Line/Disabled", bundle: .module)
        }
        public static let parking24x24Line = Image("Icons/Icons/Hotel/Parking 24x24 Line", bundle: .module)
        public enum Pet24x24Line {
          public static let disabled = Image("Icons/Icons/Hotel/Pet 24x24 Line/Disabled", bundle: .module)
        }
        public static let pet24x24Line = Image("Icons/Icons/Hotel/Pet 24x24 Line", bundle: .module)
        public enum Pool24x24Line {
          public static let disabled = Image("Icons/Icons/Hotel/Pool 24x24 Line/Disabled", bundle: .module)
        }
        public static let pool24x24Line = Image("Icons/Icons/Hotel/Pool 24x24 Line", bundle: .module)
        public enum Restaurant24x24Line {
          public static let disabled = Image("Icons/Icons/Hotel/Restaurant 24x24 Line/Disabled", bundle: .module)
        }
        public static let restaurant24x24Line = Image("Icons/Icons/Hotel/Restaurant 24x24 Line", bundle: .module)
        public enum Spa24x24Line {
          public static let disabled = Image("Icons/Icons/Hotel/Spa 24x24 Line/Disabled", bundle: .module)
        }
        public static let spa24x24Line = Image("Icons/Icons/Hotel/Spa 24x24 Line", bundle: .module)
        public enum Wifi24x24 {
          public static let disabled = Image("Icons/Icons/Hotel/Wifi 24x24/Disabled", bundle: .module)
        }
        public static let wifi24x24 = Image("Icons/Icons/Hotel/Wifi 24x24", bundle: .module)
      }
      public enum Interface {
        public static let chevronSmall16x16Blue = Image("Icons/Icons/Interface/Chevron Small 16x16 Blue", bundle: .module)
        public static let invisible24x24FillBlue = Image("Icons/Icons/Interface/Invisible 24x24 Fill Blue", bundle: .module)
        public static let lock24x2475White = Image("Icons/Icons/Interface/Lock 24x24 75% White", bundle: .module)
        public static let phone24x24 = Image("Icons/Icons/Interface/Phone 24x24", bundle: .module)
        public static let plusThin24x24Blue = Image("Icons/Icons/Interface/Plus Thin 24x24 Blue", bundle: .module)
        public static let tickThin24x24Blue = Image("Icons/Icons/Interface/Tick Thin 24x24 Blue", bundle: .module)
        public static let tickThin24x24Green = Image("Icons/Icons/Interface/Tick Thin 24x24 Green", bundle: .module)
        public static let tickThinCircle72x72Green = Image("Icons/Icons/Interface/Tick Thin Circle 72x72 Green", bundle: .module)
        public static let visible24x24FillBlue = Image("Icons/Icons/Interface/Visible 24x24 Fill Blue", bundle: .module)
      }
    }
    public enum Interface {
      public static let bell24x24Fill = Image("Icons/Interface/Bell 24x24 Fill", bundle: .module)
      public static let bell24x24Line1 = Image("Icons/Interface/Bell 24x24 Line-1", bundle: .module)
      public static let bell24x24Line = Image("Icons/Interface/Bell 24x24 Line", bundle: .module)
      public static let bin24x24Fill = Image("Icons/Interface/Bin 24x24 Fill", bundle: .module)
      public static let bin24x24Line = Image("Icons/Interface/Bin 24x24 Line", bundle: .module)
      public static let bulb24x24Fill = Image("Icons/Interface/Bulb 24x24 Fill", bundle: .module)
      public static let bulb24x24Line = Image("Icons/Interface/Bulb 24x24 Line", bundle: .module)
      public static let calendar24x24Fill = Image("Icons/Interface/Calendar 24x24 Fill", bundle: .module)
      public static let calendar24x24Line = Image("Icons/Interface/Calendar 24x24 Line", bundle: .module)
      public static let checkin24x24Fill = Image("Icons/Interface/Checkin 24x24  Fill", bundle: .module)
      public static let checkin24x24Line = Image("Icons/Interface/Checkin 24x24 Line", bundle: .module)
      public static let checkout24x24Fill = Image("Icons/Interface/Checkout 24x24 Fill", bundle: .module)
      public static let checkout24x24Line = Image("Icons/Interface/Checkout 24x24 Line", bundle: .module)
      public static let click24x24Fill = Image("Icons/Interface/Click 24x24 Fill", bundle: .module)
      public static let click24x24Line = Image("Icons/Interface/Click 24x24 Line", bundle: .module)
      public static let clickRipple24x24Fill = Image("Icons/Interface/Click ripple 24x24 Fill", bundle: .module)
      public static let clickRipple24x24Line = Image("Icons/Interface/Click ripple 24x24 Line", bundle: .module)
      public static let clock24x24Fill = Image("Icons/Interface/Clock 24x24 Fill", bundle: .module)
      public static let clock24x24Line = Image("Icons/Interface/Clock 24x24 Line", bundle: .module)
      public static let copy24x24Fill = Image("Icons/Interface/Copy 24x24 Fill", bundle: .module)
      public static let copy24x24Line = Image("Icons/Interface/Copy 24x24 Line", bundle: .module)
      public static let dashboard24x24Fill = Image("Icons/Interface/Dashboard 24x24 Fill", bundle: .module)
      public static let dashboard24x24Line = Image("Icons/Interface/Dashboard 24x24 Line", bundle: .module)
      public static let eye24x24Fill = Image("Icons/Interface/Eye 24x24 Fill", bundle: .module)
      public static let eye24x24Line = Image("Icons/Interface/Eye 24x24 Line", bundle: .module)
      public static let eyeCrossed24x24Fill = Image("Icons/Interface/Eye crossed 24x24 Fill", bundle: .module)
      public static let eyeCrossed24x24Line = Image("Icons/Interface/Eye crossed 24x24 Line", bundle: .module)
      public static let filters24x24Fill = Image("Icons/Interface/Filters 24x24 Fill", bundle: .module)
      public static let filters24x24Line = Image("Icons/Interface/Filters 24x24 Line", bundle: .module)
      public static let filtersCrossed24x24Fill = Image("Icons/Interface/Filters crossed 24x24 Fill", bundle: .module)
      public static let filtersCrossed24x24Line = Image("Icons/Interface/Filters crossed 24x24 Line", bundle: .module)
      public static let flag24x24Fill = Image("Icons/Interface/Flag 24x24 Fill", bundle: .module)
      public static let flag24x24Line = Image("Icons/Interface/Flag 24x24 Line", bundle: .module)
      public static let gearWheel24x24Fill = Image("Icons/Interface/Gear wheel 24x24 Fill", bundle: .module)
      public static let gearWheel24x24Line = Image("Icons/Interface/Gear wheel 24x24 Line", bundle: .module)
      public static let gridSmall24x24Fill1 = Image("Icons/Interface/Grid small 24x24 Fill-1", bundle: .module)
      public static let gridSmall24x24Fill = Image("Icons/Interface/Grid small 24x24 Fill", bundle: .module)
      public static let gridSmall24x24Line1 = Image("Icons/Interface/Grid small 24x24 Line-1", bundle: .module)
      public static let gridSmall24x24Line = Image("Icons/Interface/Grid small 24x24 Line", bundle: .module)
      public enum Large {
        public static let bell48x48Fill = Image("Icons/Interface/Large/Bell 48x48 Fill", bundle: .module)
        public static let bell48x48Line = Image("Icons/Interface/Large/Bell 48x48 Line", bundle: .module)
        public static let calendarTick48x48Fill = Image("Icons/Interface/Large/Calendar tick 48x48 Fill", bundle: .module)
        public static let calendarTick48x48Line = Image("Icons/Interface/Large/Calendar tick 48x48 Line", bundle: .module)
        public static let clock48x48Fill = Image("Icons/Interface/Large/Clock 48x48 Fill", bundle: .module)
        public static let clock48x48Line = Image("Icons/Interface/Large/Clock 48x48 Line", bundle: .module)
        public static let pencil48x48Fill1 = Image("Icons/Interface/Large/Pencil 48x48 Fill-1", bundle: .module)
        public static let pencil48x48Fill = Image("Icons/Interface/Large/Pencil 48x48 Fill", bundle: .module)
        public static let pencil48x48Line1 = Image("Icons/Interface/Large/Pencil 48x48 Line-1", bundle: .module)
        public static let pencil48x48Line = Image("Icons/Interface/Large/Pencil 48x48 Line", bundle: .module)
        public static let play48x48Fill = Image("Icons/Interface/Large/Play 48x48 Fill", bundle: .module)
        public static let play48x48Line = Image("Icons/Interface/Large/Play 48x48 Line", bundle: .module)
        public static let scale48x48Fill = Image("Icons/Interface/Large/Scale 48x48 Fill", bundle: .module)
        public static let scale48x48Line = Image("Icons/Interface/Large/Scale 48x48 Line", bundle: .module)
        public static let tools48x48Fill = Image("Icons/Interface/Large/Tools 48x48 Fill", bundle: .module)
        public static let tools48x48Line = Image("Icons/Interface/Large/Tools 48x48 Line", bundle: .module)
        public static let trivagoNetwork48x48Fill = Image("Icons/Interface/Large/trivago network 48x48 Fill", bundle: .module)
        public static let trivagoNetwork48x48Line = Image("Icons/Interface/Large/trivago network 48x48 Line", bundle: .module)
      }
      public static let lock24x24Fill = Image("Icons/Interface/Lock 24x24 Fill", bundle: .module)
      public static let lock24x24Line = Image("Icons/Interface/Lock 24x24 Line", bundle: .module)
      public static let lockOpen24x24Fill = Image("Icons/Interface/Lock open 24x24 Fill", bundle: .module)
      public static let lockOpen24x24Line = Image("Icons/Interface/Lock open 24x24 Line", bundle: .module)
      public static let merge24x24Fill = Image("Icons/Interface/Merge 24x24 Fill", bundle: .module)
      public static let merge24x24Line = Image("Icons/Interface/Merge 24x24 Line", bundle: .module)
      public static let pencil24x24Fill = Image("Icons/Interface/Pencil 24x24 Fill", bundle: .module)
      public static let pencil24x24Line = Image("Icons/Interface/Pencil 24x24 Line", bundle: .module)
      public static let peperPencil24x24Fill = Image("Icons/Interface/Peper pencil 24x24 Fill", bundle: .module)
      public static let peperPencil24x24Line = Image("Icons/Interface/Peper pencil 24x24 Line", bundle: .module)
      public static let play24x24Fill = Image("Icons/Interface/Play 24x24 Fill", bundle: .module)
      public static let play24x24Line = Image("Icons/Interface/Play 24x24 Line", bundle: .module)
      public static let questionMark24x24 = Image("Icons/Interface/Question mark 24x24", bundle: .module)
      public static let questionMarkCircle24x24Fill = Image("Icons/Interface/Question mark circle 24x24 Fill", bundle: .module)
      public static let questionMarkCircle24x24Line = Image("Icons/Interface/Question mark circle 24x24 Line", bundle: .module)
      public static let recent24x24Fill = Image("Icons/Interface/Recent 24x24 Fill", bundle: .module)
      public static let recent24x24Line = Image("Icons/Interface/Recent 24x24 Line", bundle: .module)
      public static let refresh24x24Fill = Image("Icons/Interface/Refresh 24x24 Fill", bundle: .module)
      public static let refresh24x24Line = Image("Icons/Interface/Refresh 24x24 Line", bundle: .module)
      public static let replace24x24Fill = Image("Icons/Interface/Replace 24x24 Fill", bundle: .module)
      public static let replace24x24Line = Image("Icons/Interface/Replace 24x24 Line", bundle: .module)
      public static let scale24x24Fill = Image("Icons/Interface/Scale 24x24 Fill", bundle: .module)
      public static let scale24x24Line = Image("Icons/Interface/Scale 24x24 Line", bundle: .module)
      public static let unavailable24x24Fill = Image("Icons/Interface/Unavailable 24x24 Fill", bundle: .module)
      public static let unavailable24x24Line = Image("Icons/Interface/Unavailable 24x24 Line", bundle: .module)
      public static let update24x24Fill = Image("Icons/Interface/Update 24x24 Fill", bundle: .module)
      public static let update24x24Line = Image("Icons/Interface/Update 24x24 Line", bundle: .module)
      public static let visits24x24Fill = Image("Icons/Interface/Visits 24x24 Fill", bundle: .module)
      public static let visits24x24Line = Image("Icons/Interface/Visits 24x24 Line", bundle: .module)
      public static let wrench24x24Fill = Image("Icons/Interface/Wrench 24x24 Fill", bundle: .module)
      public static let wrench24x24Line = Image("Icons/Interface/Wrench 24x24 Line", bundle: .module)
    }
    public enum ItemElement {
      public static let bookmarkIconActive = Image("Icons/ItemElement/BookmarkIcon Active", bundle: .module)
      public static let bookmarkIconInactive = Image("Icons/ItemElement/BookmarkIcon_Inactive", bundle: .module)
      public static let bookmarkInactiveJuri = Image("Icons/ItemElement/Bookmark_InactiveJuri", bundle: .module)
      public static let distance = Image("Icons/ItemElement/Distance", bundle: .module)
      public static let heartFilled = Image("Icons/ItemElement/HeartFilled", bundle: .module)
      public static let heartUnfilled = Image("Icons/ItemElement/HeartUnfilled", bundle: .module)
      public static let heartUnfilledJuri = Image("Icons/ItemElement/HeartUnfilledJuri", bundle: .module)
      public static let hotelStar = Image("Icons/ItemElement/HotelStar", bundle: .module)
    }
    public static let link = Image("Icons/Link", bundle: .module)
    public enum Navigation {
      public static let backButton = Image("Icons/Navigation/Back_Button", bundle: .module)
      public static let chevronCollapse = Image("Icons/Navigation/Chevron_Collapse", bundle: .module)
      public static let chevronCollapseInactive = Image("Icons/Navigation/Chevron_Collapse_Inactive", bundle: .module)
      public static let chevronExpand = Image("Icons/Navigation/Chevron_Expand", bundle: .module)
      public static let chevronExpandInactive = Image("Icons/Navigation/Chevron_Expand_Inactive", bundle: .module)
      public static let chevronLeft = Image("Icons/Navigation/Chevron_Left", bundle: .module)
      public static let chevronRightGreen = Image("Icons/Navigation/Chevron_Right Green", bundle: .module)
      public static let chevronRight = Image("Icons/Navigation/Chevron_Right", bundle: .module)
      public static let close1 = Image("Icons/Navigation/Close-1", bundle: .module)
      public static let close = Image("Icons/Navigation/Close", bundle: .module)
      public static let closeInactive = Image("Icons/Navigation/Close_Inactive", bundle: .module)
    }
    public enum People {
      public static let adult24x24Fill = Image("Icons/People/Adult 24x24 Fill", bundle: .module)
      public static let adult24x24Line = Image("Icons/People/Adult 24x24 Line", bundle: .module)
      public static let adultPlus24x24Fill = Image("Icons/People/Adult plus 24x24 Fill", bundle: .module)
      public static let adultPlus24x24Line = Image("Icons/People/Adult plus 24x24 Line", bundle: .module)
      public static let adultPresenting24x24Fill = Image("Icons/People/Adult presenting 24x24 Fill", bundle: .module)
      public static let adultPresenting24x24Line = Image("Icons/People/Adult presenting 24x24 Line", bundle: .module)
      public static let adultsThree24x24Fill = Image("Icons/People/Adults three 24x24 Fill", bundle: .module)
      public static let adultsThree24x24Line = Image("Icons/People/Adults three 24x24 Line", bundle: .module)
      public static let adultsTwo24x24Fill = Image("Icons/People/Adults two 24x24 Fill", bundle: .module)
      public static let adultsTwo24x24Line = Image("Icons/People/Adults two 24x24 Line", bundle: .module)
      public static let adultsTwoKid24x24Fill = Image("Icons/People/Adults two kid 24x24 Fill", bundle: .module)
      public static let adultsTwoKid24x24Line = Image("Icons/People/Adults two kid 24x24 Line", bundle: .module)
      public static let couple24x24Fill = Image("Icons/People/Couple 24x24 Fill", bundle: .module)
      public static let couple24x24Line = Image("Icons/People/Couple 24x24 Line", bundle: .module)
      public static let gent24x24Fill = Image("Icons/People/Gent 24x24 Fill", bundle: .module)
      public static let gent24x24Line = Image("Icons/People/Gent 24x24 Line", bundle: .module)
      public static let infoDesk24x24Fill = Image("Icons/People/Info Desk 24x24 Fill", bundle: .module)
      public static let infoDesk24x24Line = Image("Icons/People/Info Desk 24x24 Line", bundle: .module)
      public static let lady24x24Fill = Image("Icons/People/Lady 24x24 Fill", bundle: .module)
      public static let lady24x24Line = Image("Icons/People/Lady 24x24 Line", bundle: .module)
      public enum Large {
        public static let adultRefresh48x48Fill = Image("Icons/People/Large/Adult refresh 48x48 Fill", bundle: .module)
        public static let adultRefresh48x48Line = Image("Icons/People/Large/Adult refresh 48x48 Line", bundle: .module)
      }
      public static let pedestrian24x24Fill = Image("Icons/People/Pedestrian 24x24 Fill", bundle: .module)
      public static let pedestrian24x24Line = Image("Icons/People/Pedestrian 24x24 Line", bundle: .module)
      public static let wheelchair24x24Fill = Image("Icons/People/Wheelchair 24x24 Fill", bundle: .module)
      public static let wheelchair24x24Line = Image("Icons/People/Wheelchair 24x24 Line", bundle: .module)
    }
    public enum Rewards {
      public static let coins24x24Fill = Image("Icons/Rewards/Coins 24x24 Fill", bundle: .module)
      public static let coins24x24Line = Image("Icons/Rewards/Coins 24x24 Line", bundle: .module)
      public static let graduationCap24x24Fill = Image("Icons/Rewards/Graduation cap 24x24 Fill", bundle: .module)
      public static let graduationCap24x24Line = Image("Icons/Rewards/Graduation cap 24x24 Line", bundle: .module)
      public static let heart24x24Fill = Image("Icons/Rewards/Heart 24x24 Fill", bundle: .module)
      public static let heart24x24Line = Image("Icons/Rewards/Heart 24x24 Line", bundle: .module)
      public enum Large {
        public static let cardPayment48x48Fill = Image("Icons/Rewards/Large/Card payment 48x48 Fill", bundle: .module)
        public static let cardPayment48x48Line = Image("Icons/Rewards/Large/Card payment 48x48 Line", bundle: .module)
        public static let coinPiles48x48Fill = Image("Icons/Rewards/Large/Coin piles 48x48 Fill", bundle: .module)
        public static let coinPiles48x48Line = Image("Icons/Rewards/Large/Coin piles 48x48 Line", bundle: .module)
        public static let coins48x48Fill = Image("Icons/Rewards/Large/Coins 48x48 Fill", bundle: .module)
        public static let coins48x48Line = Image("Icons/Rewards/Large/Coins 48x48 Line", bundle: .module)
      }
      public static let medal24x24Fill = Image("Icons/Rewards/Medal 24x24 Fill", bundle: .module)
      public static let medal24x24Line = Image("Icons/Rewards/Medal 24x24 Line", bundle: .module)
      public static let revenue24x24Fill = Image("Icons/Rewards/Revenue 24x24 Fill", bundle: .module)
      public static let revenue24x24Line = Image("Icons/Rewards/Revenue 24x24 Line", bundle: .module)
      public static let star24x24Fill1 = Image("Icons/Rewards/Star 24x24 Fill-1", bundle: .module)
      public static let star24x24Fill = Image("Icons/Rewards/Star 24x24 Fill", bundle: .module)
      public static let starCrossed24x24Fill = Image("Icons/Rewards/Star crossed 24x24 Fill", bundle: .module)
      public static let starCrossed24x24Line = Image("Icons/Rewards/Star crossed 24x24 Line", bundle: .module)
      public static let starSmall12x12 = Image("Icons/Rewards/Star small 12x12", bundle: .module)
      public static let starSmallCrossed12x12 = Image("Icons/Rewards/Star small crossed 12x12", bundle: .module)
      public static let starSmallHalf12x12 = Image("Icons/Rewards/Star small half 12x12", bundle: .module)
      public static let stars136x36 = Image("Icons/Rewards/Stars 1 36x36", bundle: .module)
      public static let stars236x36 = Image("Icons/Rewards/Stars 2 36x36", bundle: .module)
      public static let stars336x36 = Image("Icons/Rewards/Stars 3 36x36", bundle: .module)
      public static let stars436x36 = Image("Icons/Rewards/Stars 4 36x36", bundle: .module)
      public static let stars536x36 = Image("Icons/Rewards/Stars 5 36x36", bundle: .module)
      public static let sunSmall12x12 = Image("Icons/Rewards/Sun small 12x12", bundle: .module)
      public static let sunSmallCrossed12x12 = Image("Icons/Rewards/Sun small crossed 12x12", bundle: .module)
      public static let suns136x36 = Image("Icons/Rewards/Suns 1 36x36", bundle: .module)
      public static let suns236x36 = Image("Icons/Rewards/Suns 2 36x36", bundle: .module)
      public static let suns336x36 = Image("Icons/Rewards/Suns 3 36x36", bundle: .module)
      public static let suns436x36 = Image("Icons/Rewards/Suns 4 36x36", bundle: .module)
      public static let suns536x36 = Image("Icons/Rewards/Suns 5 36x36", bundle: .module)
      public static let superior12x12 = Image("Icons/Rewards/Superior 12x12", bundle: .module)
      public static let thumb24x24Fill = Image("Icons/Rewards/Thumb 24x24 Fill", bundle: .module)
      public static let thumb24x24Line = Image("Icons/Rewards/Thumb 24x24 Line", bundle: .module)
      public static let trophy24x24Fill = Image("Icons/Rewards/Trophy 24x24 Fill", bundle: .module)
      public static let trophy24x24Line = Image("Icons/Rewards/Trophy 24x24 Line", bundle: .module)
    }
    public enum Social {
      public static let export24x24Line1 = Image("Icons/Social/Export 24x24 Line-1", bundle: .module)
      public static let export24x24Line = Image("Icons/Social/Export 24x24 Line", bundle: .module)
      public static let facebook24x24 = Image("Icons/Social/Facebook 24x24", bundle: .module)
      public static let g24x24 = Image("Icons/Social/G+ 24x24", bundle: .module)
      public static let git24x24 = Image("Icons/Social/Git 24x24", bundle: .module)
      public static let instagram24x24 = Image("Icons/Social/Instagram 24x24", bundle: .module)
      public enum Large {
        public static let share48x48Fill = Image("Icons/Social/Large/Share 48x48 Fill", bundle: .module)
        public static let share48x48Line = Image("Icons/Social/Large/Share 48x48 Line", bundle: .module)
      }
      public static let link24x24 = Image("Icons/Social/Link 24x24", bundle: .module)
      public static let linkedIn24x24 = Image("Icons/Social/LinkedIn 24x24", bundle: .module)
      public static let pinterest24x24 = Image("Icons/Social/Pinterest 24x24", bundle: .module)
      public static let rss24x24 = Image("Icons/Social/RSS 24x24", bundle: .module)
      public static let share24x24Fill = Image("Icons/Social/Share 24x24 Fill", bundle: .module)
      public static let share24x24Line = Image("Icons/Social/Share 24x24 Line", bundle: .module)
      public static let twitter24x24 = Image("Icons/Social/Twitter 24x24", bundle: .module)
      public static let vk24x24 = Image("Icons/Social/VK 24x24", bundle: .module)
      public static let whatsApp24x24 = Image("Icons/Social/WhatsApp 24x24", bundle: .module)
      public static let xing24x24 = Image("Icons/Social/Xing 24x24", bundle: .module)
      public static let youtube24x24 = Image("Icons/Social/Youtube 24x24", bundle: .module)
    }
    public enum Spinner {
      public static let dark = Image("Icons/Spinner/Dark", bundle: .module)
      public static let light = Image("Icons/Spinner/Light", bundle: .module)
    }
    public enum Steppers {
      public static let minusDisabled = Image("Icons/Steppers/Minus Disabled", bundle: .module)
      public static let minus = Image("Icons/Steppers/Minus", bundle: .module)
      public static let plusDisabled = Image("Icons/Steppers/Plus Disabled", bundle: .module)
      public static let plus = Image("Icons/Steppers/Plus", bundle: .module)
    }
    public enum Swipe {
      public static let trashCan40x40 = Image("Icons/Swipe/TrashCan40x40", bundle: .module)
    }
    public enum TabBar {
      public static let bookmark = Image("Icons/TabBar/Bookmark", bundle: .module)
      public static let favorites = Image("Icons/TabBar/Favorites", bundle: .module)
      public static let profile = Image("Icons/TabBar/Profile", bundle: .module)
      public static let search = Image("Icons/TabBar/Search", bundle: .module)
      public static let settings = Image("Icons/TabBar/Settings", bundle: .module)
      public enum States {
        public static let favouritesActive = Image("Icons/TabBar/States/FavouritesActive", bundle: .module)
        public static let settingsActive = Image("Icons/TabBar/States/SettingsActive", bundle: .module)
        public static let staysActive1 = Image("Icons/TabBar/States/StaysActive-1", bundle: .module)
        public static let staysActive = Image("Icons/TabBar/States/StaysActive", bundle: .module)
      }
      public static let stays = Image("Icons/TabBar/Stays", bundle: .module)
      public static let weekend = Image("Icons/TabBar/Weekend", bundle: .module)
    }
    public enum Technology {
      public static let ad24x24Fill = Image("Icons/Technology/Ad 24x24 Fill", bundle: .module)
      public static let ad24x24Line = Image("Icons/Technology/Ad 24x24 Line", bundle: .module)
      public static let antenna24x24Fill = Image("Icons/Technology/Antenna 24x24 Fill", bundle: .module)
      public static let antenna24x24Line = Image("Icons/Technology/Antenna 24x24 Line", bundle: .module)
      public static let browser24x24Fill = Image("Icons/Technology/Browser 24x24 Fill", bundle: .module)
      public static let browser24x24Line = Image("Icons/Technology/Browser 24x24 Line", bundle: .module)
      public static let creditCard24x24Fill = Image("Icons/Technology/Credit card 24x24 Fill", bundle: .module)
      public static let creditCard24x24Line = Image("Icons/Technology/Credit card 24x24 Line", bundle: .module)
      public static let desktop24x24Fill = Image("Icons/Technology/Desktop 24x24 Fill", bundle: .module)
      public static let desktop24x24Line = Image("Icons/Technology/Desktop 24x24 Line", bundle: .module)
      public static let download24x24Fill = Image("Icons/Technology/Download 24x24 Fill", bundle: .module)
      public static let download24x24Line = Image("Icons/Technology/Download 24x24 Line", bundle: .module)
      public static let electricity24x24Fill = Image("Icons/Technology/Electricity 24x24 Fill", bundle: .module)
      public static let electricity24x24Line = Image("Icons/Technology/Electricity 24x24 Line", bundle: .module)
      public static let envelope24x24Fill = Image("Icons/Technology/Envelope 24x24 Fill", bundle: .module)
      public static let envelope24x24Line = Image("Icons/Technology/Envelope 24x24 Line", bundle: .module)
      public static let hdmi24x24Fill = Image("Icons/Technology/Hdmi 24x24 Fill", bundle: .module)
      public static let hdmi24x24Line = Image("Icons/Technology/Hdmi 24x24 Line", bundle: .module)
      public static let laptop24x24Fill = Image("Icons/Technology/Laptop 24x24 Fill", bundle: .module)
      public static let laptop24x24Line = Image("Icons/Technology/Laptop 24x24 Line", bundle: .module)
      public enum Large {
        public static let database48x48Fill = Image("Icons/Technology/Large/Database 48x48 Fill", bundle: .module)
        public static let database48x48Line = Image("Icons/Technology/Large/Database 48x48 Line", bundle: .module)
        public static let devices48x48Fill = Image("Icons/Technology/Large/Devices 48x48 Fill", bundle: .module)
        public static let devices48x48Line = Image("Icons/Technology/Large/Devices 48x48 Line", bundle: .module)
        public static let envelopeOne48x48Fill = Image("Icons/Technology/Large/Envelope one 48x48 Fill", bundle: .module)
        public static let envelopeOne48x48Line = Image("Icons/Technology/Large/Envelope one 48x48 Line", bundle: .module)
        public static let envelopeQuestionMark48x48Line1 = Image("Icons/Technology/Large/Envelope question mark 48x48 Line-1", bundle: .module)
        public static let envelopeQuestionMark48x48Line = Image("Icons/Technology/Large/Envelope question mark 48x48 Line", bundle: .module)
        public static let presentation48x48Fill = Image("Icons/Technology/Large/Presentation 48x48 Fill", bundle: .module)
        public static let presentation48x48Line = Image("Icons/Technology/Large/Presentation 48x48 Line", bundle: .module)
        public static let presentationGraduationCap48x48Fill = Image("Icons/Technology/Large/Presentation graduation cap 48x48 Fill", bundle: .module)
        public static let presentationGraduationCap48x48Line = Image("Icons/Technology/Large/Presentation graduation cap 48x48 Line", bundle: .module)
      }
      public static let mIcrophone24x24Fill = Image("Icons/Technology/MIcrophone 24x24 Fill", bundle: .module)
      public static let microphone24x24Line = Image("Icons/Technology/Microphone 24x24 Line", bundle: .module)
      public static let microphoneCrossed24x24Fill = Image("Icons/Technology/Microphone crossed 24x24 Fill", bundle: .module)
      public static let microphoneCrossed24x24Line = Image("Icons/Technology/Microphone crossed 24x24 Line", bundle: .module)
      public static let microscope24x24Fill = Image("Icons/Technology/Microscope 24x24 Fill", bundle: .module)
      public static let microscope24x24Line = Image("Icons/Technology/Microscope 24x24 Line", bundle: .module)
      public static let mobile24x24Fill = Image("Icons/Technology/Mobile 24x24 Fill", bundle: .module)
      public static let mobile24x24Line = Image("Icons/Technology/Mobile 24x24 Line", bundle: .module)
      public static let phone24x24Fill = Image("Icons/Technology/Phone 24x24 Fill", bundle: .module)
      public static let phone24x24Line = Image("Icons/Technology/Phone 24x24 Line", bundle: .module)
      public static let phoneCrossed24x24Fill = Image("Icons/Technology/Phone crossed 24x24 Fill", bundle: .module)
      public static let phoneCrossed24x24Line = Image("Icons/Technology/Phone crossed 24x24 Line", bundle: .module)
      public static let printer24x24Fill = Image("Icons/Technology/Printer 24x24 Fill", bundle: .module)
      public static let printer24x24Line = Image("Icons/Technology/Printer 24x24 Line", bundle: .module)
      public static let projector24x24Fill = Image("Icons/Technology/Projector 24x24 Fill", bundle: .module)
      public static let projector24x24Line = Image("Icons/Technology/Projector 24x24 Line", bundle: .module)
      public static let screen24x24Fill = Image("Icons/Technology/Screen 24x24 Fill", bundle: .module)
      public static let screen24x24Line = Image("Icons/Technology/Screen 24x24 Line", bundle: .module)
      public static let sound24x24Fill = Image("Icons/Technology/Sound 24x24 Fill", bundle: .module)
      public static let sound24x24Line = Image("Icons/Technology/Sound 24x24 Line", bundle: .module)
      public static let speaker24x24Fill = Image("Icons/Technology/Speaker 24x24 Fill", bundle: .module)
      public static let speaker24x24Line = Image("Icons/Technology/Speaker 24x24 line", bundle: .module)
      public static let tv24x24Fill = Image("Icons/Technology/Tv 24x24 Fill", bundle: .module)
      public static let tv24x24Line = Image("Icons/Technology/Tv 24x24 Line", bundle: .module)
      public static let webcamMicrophone24x24Fill = Image("Icons/Technology/Webcam Microphone 24x24 Fill", bundle: .module)
      public static let webcamMicrophone24x24Line = Image("Icons/Technology/Webcam Microphone 24x24 Line", bundle: .module)
      public static let wifi24x24 = Image("Icons/Technology/Wifi 24x24", bundle: .module)
    }
    public enum Travel {
      public static let anchor24x24Fill = Image("Icons/Travel/Anchor 24x24 Fill", bundle: .module)
      public static let anchor24x24Line = Image("Icons/Travel/Anchor 24x24 Line", bundle: .module)
      public static let bird24x24Fill = Image("Icons/Travel/Bird 24x24 Fill", bundle: .module)
      public static let bird24x24Line = Image("Icons/Travel/Bird 24x24 Line", bundle: .module)
      public static let briefcase24x24Fill = Image("Icons/Travel/Briefcase 24x24 Fill", bundle: .module)
      public static let briefcase24x24Line = Image("Icons/Travel/Briefcase 24x24 Line", bundle: .module)
      public static let car24x24Fill = Image("Icons/Travel/Car 24x24 Fill", bundle: .module)
      public static let car24x24Line = Image("Icons/Travel/Car 24x24 Line", bundle: .module)
      public static let diplomat24x24Fill = Image("Icons/Travel/Diplomat 24x24 Fill", bundle: .module)
      public static let diplomat24x24Line = Image("Icons/Travel/Diplomat 24x24 Line", bundle: .module)
      public static let earth24x24Line1 = Image("Icons/Travel/Earth 24x24 Line-1", bundle: .module)
      public static let earth24x24Line = Image("Icons/Travel/Earth 24x24 Line", bundle: .module)
      public static let fire24x24Fill = Image("Icons/Travel/Fire 24x24 Fill", bundle: .module)
      public static let fire24x24Line = Image("Icons/Travel/Fire 24x24 Line", bundle: .module)
      public enum Large {
        public static let diplomat48x48Fill = Image("Icons/Travel/Large/Diplomat 48x48 Fill", bundle: .module)
        public static let diplomat48x48Line = Image("Icons/Travel/Large/Diplomat 48x48 Line", bundle: .module)
        public static let locationPinMap48x48Fill = Image("Icons/Travel/Large/Location pin map 48x48 Fill", bundle: .module)
        public static let locationPinMap48x48Line = Image("Icons/Travel/Large/Location pin map 48x48 Line", bundle: .module)
        public static let moon48x48Fill = Image("Icons/Travel/Large/Moon 48x48 Fill", bundle: .module)
        public static let moon48x48Line = Image("Icons/Travel/Large/Moon 48x48 Line", bundle: .module)
        public static let passportFlightTickets48x48Fill = Image("Icons/Travel/Large/Passport flight tickets 48x48 Fill", bundle: .module)
        public static let passportFlightTickets48x48Line = Image("Icons/Travel/Large/Passport flight tickets 48x48 Line", bundle: .module)
      }
      public static let leaves24x24Fill = Image("Icons/Travel/Leaves 24x24 Fill", bundle: .module)
      public static let leaves24x24Line = Image("Icons/Travel/Leaves 24x24 Line", bundle: .module)
      public static let locationPin24x24Fill = Image("Icons/Travel/Location pin 24x24 Fill", bundle: .module)
      public static let locationPin24x24Line = Image("Icons/Travel/Location pin 24x24 Line", bundle: .module)
      public static let map24x24Fill = Image("Icons/Travel/Map 24x24 Fill", bundle: .module)
      public static let map24x24Line = Image("Icons/Travel/Map 24x24 Line", bundle: .module)
      public static let moon24x24Fill = Image("Icons/Travel/Moon 24x24 Fill", bundle: .module)
      public static let moon24x24Line = Image("Icons/Travel/Moon 24x24 Line", bundle: .module)
      public static let plane24x24Fill = Image("Icons/Travel/Plane 24x24 Fill", bundle: .module)
      public static let plane24x24Line = Image("Icons/Travel/Plane 24x24 Line", bundle: .module)
      public static let planet24x24Fill = Image("Icons/Travel/Planet 24x24 Fill", bundle: .module)
      public static let planet24x24Line = Image("Icons/Travel/Planet 24x24 Line", bundle: .module)
      public static let shuttle24x24Fill = Image("Icons/Travel/Shuttle 24x24 Fill", bundle: .module)
      public static let shuttle24x24Line = Image("Icons/Travel/Shuttle 24x24 Line", bundle: .module)
      public static let spaceship24x24Fill = Image("Icons/Travel/Spaceship 24x24 Fill", bundle: .module)
      public static let spaceship24x24Line = Image("Icons/Travel/Spaceship 24x24 Line", bundle: .module)
      public static let target24x24Fill = Image("Icons/Travel/Target 24x24 Fill", bundle: .module)
      public static let target24x24Line = Image("Icons/Travel/Target 24x24 Line", bundle: .module)
      public static let train24x24Fill = Image("Icons/Travel/Train 24x24 Fill", bundle: .module)
      public static let train24x24Line = Image("Icons/Travel/Train 24x24 Line", bundle: .module)
      public static let traveler24x24Fill = Image("Icons/Travel/Traveler 24x24 Fill", bundle: .module)
      public static let traveler24x24Line = Image("Icons/Travel/Traveler 24x24 Line", bundle: .module)
      public static let tree24x24Fill = Image("Icons/Travel/Tree 24x24 Fill", bundle: .module)
      public static let tree24x24Line = Image("Icons/Travel/Tree 24x24 Line", bundle: .module)
      public static let trolley24x24Fill = Image("Icons/Travel/Trolley 24x24 Fill", bundle: .module)
      public static let trolley24x24Line = Image("Icons/Travel/Trolley 24x24 Line", bundle: .module)
    }
    public static let icnLogin24x24 = Image("Icons/icn_login 24x24", bundle: .module)
    public enum Platforms {
      public static let android = Image("Icons/platforms/android", bundle: .module)
      public static let apple = Image("Icons/platforms/apple", bundle: .module)
      public static let web1 = Image("Icons/platforms/web1", bundle: .module)
    }
  }
}
